<?php
echo "<div style=\"border: solid;text-align: center;margin-top:5%;padding-left: 2%;padding-right: 2%; padding-top: 2%; padding-bottom: 2%\">";
echo "<form action=\"./profile.php\" method=\"post\">";
echo "   <table>";
echo "       <tr>";
echo "           <th>Username</th>";
echo "           <td>$username</td>";
echo "       </tr>";
echo "       <tr>";
echo "           <th>Password</th>";
echo "           <td><input type=\"password\" name = 'password' value='$password'></td>";
echo "       </tr>";
echo "       <tr>";
echo "           <th>Full Name</th>";
echo "           <td><input type=\"text\" name='full_name' value='$full_name'></td>";
echo "       </tr>";
echo "       <tr>";
echo "           <th>Profile</th>";
echo "           <td><input type=\"text\" name='profile' value='$profile'></td>";
echo "       </tr>";
echo "   </table>";
echo "   <div style=\"text-align: center;padding-top: 2%\">";
echo "   <button class='btn' type=\"submit\" name=\"update_prof_confirm\">Save</button>";
echo "   <button class='btn' type=\"reset\">Reset</button>";
echo "   </div>";
echo "</form>";
echo "</div>";
